# Configurações de Conexão do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/nutritrack
spring.datasource.username=postgres
spring.datasource.password=paulokarla

# Configurações do Hibernate (A Mágica do ORM)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# O 'update' cria as tabelas automaticamente se elas não existirem
spring.jpa.hibernate.ddl-auto=update
# ==========================================
# CONFIGURAÇÕES DE E-MAIL (GMAIL)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nutritrackapp123@gmail.com
spring.mail.password=vjfzpwvictwgjran
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Mostrar os comandos SQL no terminal (excelente para depuração e para mostrar ao professor)
spring.jpa.show-sql=true